# Generated by Django 4.2.5 on 2023-09-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(choices=[('Operation', 'Operational'), ('Investment', 'Investement'), ('Recurring', 'Recurring'), ('Non-Recurring', 'Non-Recurring')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=20, null=True),
        ),
    ]
